version: '3.8'

services:
  # Servicio de MongoDB que contendrá las tres bases de datos
  mongodb:
    image: mongo:latest
    container_name: mongodb-tfc
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb-data:
    name: mongodb-tfc-data

networks:
  app-network:
    driver: bridge 