-- Eliminar la tabla si existe
DROP TABLE IF EXISTS MRCONSO;

-- Crear la tabla MRCONSO
CREATE TABLE MRCONSO (
    CUI VARCHAR(8) NOT NULL,
    LAT CHAR(3) NOT NULL,
    TS CHAR(1) NOT NULL,
    LUI VARCHAR(10) NOT NULL,
    STT VARCHAR(3) NOT NULL,
    SUI VARCHAR(10) NOT NULL,
    ISPREF CHAR(1) NOT NULL,
    AUI VARCHAR(9) NOT NULL,
    SAUI VARCHAR(255),
    SCUI VARCHAR(255),
    SDUI VARCHAR(255),
    SAB VARCHAR(20) NOT NULL,
    TTY VARCHAR(20) NOT NULL,
    CODE VARCHAR(100) NOT NULL,
    STR TEXT NOT NULL,
    SRL VARCHAR(10) NOT NULL,
    SUPPRESS CHAR(1) NOT NULL,
    CVF VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Importar los datos
LOAD DATA INFILE '/MRCONSO.RRF' 
INTO TABLE MRCONSO
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n';

-- Crear los índices después de la importación
ALTER TABLE MRCONSO 
ADD PRIMARY KEY (AUI),
ADD INDEX idx_cui (CUI),
ADD INDEX idx_str (STR(255)); 